#define COMPONENT nametags
#define COMPONENT_BEAUTIFIED Name Tags
#include "\z\a4es\addons\main\script_mod.hpp"

// #define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE
// #define ENABLE_PERFORMANCE_COUNTERS

#include "\z\a4es\addons\main\script_macros.hpp"

#define NAMETAG_2D_MAX_DISTANCE 50
#define NAMETAG_2D_MAX_DISTANCE_UNCONSCIOUS 50
#define NAMETAG_2D_FADE_IN 0.3
#define NAMETAG_2D_INIT_FADE_OUT 3600
#define NAMETAG_2D_FADE_OUT 1
#define NAMETAG_2D_NAME_SIZE 1.3
#define NAMETAG_2D_RANK_SIZE 1.05
#define NAMETAG_2D_FONT PuristaMedium

#define NAMETAG_3D_MAX_DISTANCE 50
#define NAMETAG_3D_MAX_DISTANCE_UNCONSCIOUS 50
#define NAMETAG_3D_HEIGHT_DISTANCE_FACTOR 0.035
#define NAMETAG_3D_TEXT_DISTANCE_FACTOR 0.001
#define NAMETAG_3D_TEXT_HEIGHT_DISTANCE_FACTOR 0.020
#define NAMETAG_3D_HEIGHT_OFFSET 0.35
#define NAMETAG_3D_NAME_SIZE_BASE 0.05
#define NAMETAG_3D_RANK_SIZE_BASE 0.025
#define NAMETAG_3D_ICON_SIZE 1
#define NAMETAG_3D_FONT "PuristaMedium"
#define NAMETAG_3D_TEXT_MARGIN 0.3
